### ISSUE TITLE
<link> Stylesheet not processed

### ISSUE THREAD

**Issue by Tominator89** [Prinzhorn/skrollr-stylesheets#43]
Hello i need some help. I implemented it like this

<link rel="stylesheet" href="sites/all/themes/club_leon/css/skrollr.css" data-skrollr-stylesheet="" type="text/css">

The stylesheet is available (proofed) with the contents:
.field--name-field-background-image{
    -skrollr-animation-name:parallaxscroll;
}

@-skrollr-keyframes parallaxscroll {
    bottom-top {
        margin-top:270px;
    }

```
top-bottom {
    margin-top:-270px;
}

center {
    margin-top:0px
}
```

}   

And here is my call to skrollr.init()

var s = skrollr.init({
      forceHeight: false,
      smoothScrolling: true,
      smoothScrollingDuration:0
    }); 

I tested the animation with normal skrollr and it worked but not with skrollr-stylesheet

**Comment by Prinzhorn** [comment]
This is not enough code to reproduce the issue. Also format the code correctly...

**Comment by Tominator89** [comment]
First, Sorry for the formatting. I'm new to github and don't know there is a function for this.

I Have tried different orders of including the files but nothing seems to work. I have tried it with inline css code without success. I have no javascript errors found in the console log. 

All of that files are place in the head section in this order:

`<link rel="stylesheet" href="skrollr.css" data-skrollr-stylesheet type="text/css">`
`<script src="skrollr.stylesheets.min.js"></script>`
`<script src="skrollr.min.js"></script>`
`<script src="skrollr-init.js"></script>`

Contents of skrollr.css:

``` css
.classname{
    -skrollr-animation-name:parallaxscroll;
}
@-skrollr-keyframes parallaxscroll {
    bottom-top {
        margin-top:270px;
    }

    top-bottom {
        margin-top:-270px;
    }

    center {
        margin-top:0px;
    }
}   
```

Contents of skrollr-init.js

``` javascript
  $(function() {    
    var s = skrollr.init({
      forceHeight: false,
      smoothScrolling: true,
      smoothScrollingDuration:0
    });
  });
```

I also tried adding the skrollr.css after the other js files.

If you need more information please let me know it.
